# Generated by Django 5.1.4 on 2025-01-09 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_first_name_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the message.', max_length=100)),
                ('email', models.EmailField(help_text='Email address for follow-up.', max_length=254)),
                ('phone_no', models.CharField(blank=True, help_text='Optional. Contact phone number.', max_length=15, null=True)),
                ('subject', models.CharField(help_text='Subject of the message.', max_length=255)),
                ('message', models.TextField(help_text='Detailed message from the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the message was submitted.')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the message has been addressed.')),
                ('user', models.ForeignKey(blank=True, help_text='Optional. Links to a registered user if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_meterials', models.FileField(blank=True, null=True, upload_to='course_material/')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_image/')),
                ('course_video', models.FileField(blank=True, null=True, upload_to='course_video/')),
                ('course_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('enrolled_users', models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
