# Generated by Django 5.1.4 on 2025-01-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactus_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question being asked.', max_length=255)),
                ('answer', models.TextField(help_text='The answer to the question.')),
                ('category', models.CharField(blank=True, help_text='Optional. The category this FAQ belongs to (e.g., Billing, Account).', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is visible to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this FAQ was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this FAQ was last updated.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['created_at'],
            },
        ),
    ]
