# Generated by Django 5.1.4 on 2025-01-09 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled_users',
        ),
        migrations.CreateModel(
            name='EnrolledCourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_course', models.ManyToManyField(blank=True, related_name='enrolled_courses', to='core.course')),
                ('enrolled_users', models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
