# Generated by Django 5.1.4 on 2025-01-09 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_enrolled_users_enrolledcourseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourseuser',
            name='enrolled_course',
        ),
        migrations.AddField(
            model_name='enrolledcourseuser',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='core.course'),
        ),
        migrations.AlterField(
            model_name='enrolledcourseuser',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
